# encoding: UTF-8

from objectmaphelper import *

easyDiffraction_QQuickApplicationWindow = {"title": "easyDiffraction", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
easyDiffraction_Overlay = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
modelling_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "modellingButton", "text": "Modelling", "type": "Button", "unnamed": 1, "visible": True}
analysis_Button = {"checkable": True, "container": easyDiffraction_Overlay, "id": "analysisButton", "text": "Analysis", "type": "Button", "unnamed": 1, "visible": True}
label_MnemonicLabel = {"container": easyDiffraction_Overlay, "objectName": "label", "type": "MnemonicLabel", "visible": True}
label_MnemonicLabel_2 = {"container": easyDiffraction_Overlay, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
next_Text = {"container": easyDiffraction_Overlay, "text": "Next", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_topChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "topChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
fadeOut_Rectangle = {"container": easyDiffraction_Overlay, "id": "fadeOut", "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 16, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 19, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 15, "type": "MnemonicLabel", "visible": True}
easyDiffraction_label_MnemonicLabel_4 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 18, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Image = {"container": easyDiffraction_QQuickApplicationWindow, "source": "qrc:Qml/Imports/easyDiffraction/Resources/Examples/CeCuAl3_POLARIS/cecual.png", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_tabBar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "occurrence": 2, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar = {"container": easyDiffraction_tabBar_TabBar, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
easyDiffraction_ContentArea = {"container": easyDiffraction_QQuickApplicationWindow, "type": "ContentArea", "unnamed": 1, "visible": True}
o_Home = {"container": easyDiffraction_ContentArea, "occurrence": 2, "type": "Home", "unnamed": 1, "visible": True}
tabBar_TabBar = {"container": easyDiffraction_ContentArea, "id": "tabBar", "occurrence": 5, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar_2 = {"container": tabBar_TabBar, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel = {"container": tabBar_tabBar_TabBar_2, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 38, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/plus-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Text_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 7, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 214, "type": "Rectangle", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_instrument_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new instrument.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_4 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 25, "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_a_new_phase_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import a new phase.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_tabbar_TabBar = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabbar", "type": "TabBar", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "occurrence": 2, "type": "MnemonicLabel", "visible": True}
easyDiffraction_Display_coordinate_system_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Display coordinate system", "type": "CheckBox", "unnamed": 1, "visible": True}
tabbar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabbar_TabBar, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Rectangle_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 149, "type": "Rectangle", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_2 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/play-circle.svg", "type": "IconImage", "visible": True}
easyDiffraction_Slider = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Slider", "unnamed": 1, "visible": True}
easyDiffraction_Next_step_Summary_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Next step: Summary", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_5 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 23, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Rectangle_3 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 169, "type": "Rectangle", "unnamed": 1, "visible": True}
prev_Text = {"container": easyDiffraction_Overlay, "text": "Prev", "type": "Text", "unnamed": 1, "visible": True}
click_here_to_add_or_import_new_data_Text = {"container": easyDiffraction_Overlay, "text": "Click here to add or import new data.", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Overlay_2 = {"container": easyDiffraction_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": False}
easyDiffraction_tabBar_TabBar_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
easyDiffraction_Text_3 = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "label", "occurrence": 4, "type": "MnemonicLabel", "visible": True}
tabBar_Instrument_Model_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Instrument Model", "type": "Button", "unnamed": 1, "visible": True}
tabBar_Experimental_Data_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experiment", "type": "Experiment", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_3 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "qrc:Qml/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/bug.svg", "type": "IconImage", "visible": True}
easyDiffraction_Program_Preferences_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Program Preferences", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_Animated_Intro_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show Animated Intro", "type": "CheckBox", "unnamed": 1, "visible": True}
appIcon_Image = {"container": easyDiffraction_Overlay, "id": "appIcon", "source": "qrc:Qml/Imports/easyDiffraction/Resources/Icons/App.svg", "type": "Image", "unnamed": 1, "visible": True}
easyDiffraction_Open_another_project_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Open another project", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_4 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 17, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_6 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 15, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 17, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Button_2 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "occurrence": 18, "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Text_7 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "file::/Imports/easyAnalysis/Resources/Fonts/Awesome/svgs/file-upload.svg", "type": "IconImage", "visible": True}
easyDiffraction_Fe3O4_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Fe3O4", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_5 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 20, "type": "MnemonicLabel", "visible": True}
easyDiffraction_chart_QtDataVisualization_DeclarativeScatter = {"container": easyDiffraction_QQuickApplicationWindow, "id": "chart", "type": "QtDataVisualization::DeclarativeScatter", "unnamed": 1, "visible": True}
easyDiffraction_StackLayout = {"container": easyDiffraction_QQuickApplicationWindow, "type": "StackLayout", "unnamed": 1, "visible": True}
easyDiffraction_ColumnLayout = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 2, "type": "ColumnLayout", "unnamed": 1, "visible": True}
easyDiffraction_ApplicationWindow_ContentItem = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "ApplicationWindow", "type": "ContentItem", "visible": True}
easyDiffraction_label_MnemonicLabel_6 = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experiment", "type": "Experiment", "unnamed": 1, "visible": True}
tabBar_Home_Button = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Sample", "type": "Sample", "unnamed": 1, "visible": True}
easyDiffraction_Experimental_Data_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Experimental Data", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_7 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 22, "type": "MnemonicLabel", "visible": True}
easyDiffraction_contentListView_ListView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "type": "ListView", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox = {"checkable": True, "container": easyDiffraction_ContentArea, "occurrence": 2, "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_Start_fitting_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "pausePlayButton", "text": "Start fitting", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Show_User_Guides_CheckBox = {"checkable": True, "container": easyDiffraction_QQuickApplicationWindow, "text": "Show User Guides", "type": "CheckBox", "unnamed": 1, "visible": True}
easyDiffraction_headerTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "headerTableView", "type": "TableView", "unnamed": 1, "visible": True}
headerTableView_x_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "x", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_y_obs_up_Text = {"container": easyDiffraction_ContentArea, "text": "y_obs_up", "type": "Text", "unnamed": 1, "visible": True}
headerTableView_sy_obs_up_Text = {"container": easyDiffraction_headerTableView_TableView, "text": "sy_obs_up", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_contentTableView_TableView = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentTableView", "type": "TableView", "unnamed": 1, "visible": True}
contentTableView_TextInput = {"backgroundcolor": "#ffffff", "container": easyDiffraction_contentTableView_TableView, "echoMode": 0, "occurrence": 8, "type": "TextInput", "unnamed": 1, "visible": True}
tabBar_Text_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar_2, "text": "Text View", "type": "TabButton", "unnamed": 1, "visible": True}
tabBar_Plot_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Plot View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_Text_8 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 35, "type": "Text", "unnamed": 1, "visible": True}
tabBar_Structure_View_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Structure View", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_6 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "type": "Preferences", "unnamed": 1, "visible": True}
easyDiffraction_ColumnLayout_2 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 8, "type": "ColumnLayout", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_7 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Symmetry and cell parameters", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_TextField = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_TextField_2 = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "occurrence": 2, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_TextField_3 = {"backgroundcolor": "#00000000", "container": easyDiffraction_QQuickApplicationWindow, "echoMode": 0, "occurrence": 3, "type": "TextField", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_2 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 2, "type": "ListView", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_2 = {"container": easyDiffraction_contentListView_ListView_2, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_90_0000_Text_2 = {"container": contentListView_contentRow_Rectangle_2, "occurrence": 3, "text": "90.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_90_0000_Text = {"container": contentListView_contentRow_Rectangle_2, "text": "90.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text_3 = {"container": easyDiffraction_ContentArea, "text": "6.9581", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text_2 = {"container": easyDiffraction_ContentArea, "text": "5.3968", "type": "Text", "unnamed": 1, "visible": True}
contentRow_8_5500_Text = {"container": easyDiffraction_ContentArea, "text": "8.4779", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_8 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "group1", "title": "Symmetry and cell parameters", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_9 = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "titleArea", "text": "Atoms, atomic coordinates and occupations", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_3 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 3, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_Color_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Color", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_3 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_button_Button = {"checkable": False, "container": contentListView_contentRow_Rectangle_3, "id": "button", "type": "Button", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_5 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Rectangle = {"container": contentListView_contentRow_Rectangle_5, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_O1_Text = {"container": contentListView_contentRow_Rectangle_5, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_4 = {"container": easyDiffraction_contentListView_ListView_3, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Fe3B_Text = {"container": easyDiffraction_ContentArea, "text": "S", "type": "Text", "unnamed": 1, "visible": True}
contentRow_Fe3A_Text = {"container": easyDiffraction_ContentArea, "text": "Pb", "type": "Text", "unnamed": 1, "visible": True}
contentRow_1_0000_Text = {"container": contentListView_contentRow_Rectangle_5, "text": "1.0000", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Remove_all_atoms_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Remove all atoms", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_Add_new_atom_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "text": "Add new atom", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_4 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 4, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_Uiso_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Uiso", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_U23_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "U23", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_U11_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "U11", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Type_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "Type", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Label_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 3, "text": "Label", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_6 = {"container": easyDiffraction_contentListView_ListView_4, "id": "contentRow", "index": 0, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_uani_Text = {"container": easyDiffraction_ContentArea, "occurrence": 2, "text": "Uiso", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_7 = {"container": easyDiffraction_contentListView_ListView_4, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "occurrence": 10, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text = {"container": contentListView_contentRow_Rectangle_7, "occurrence": 5, "type": "Text", "unnamed": 1, "visible": True}
contentRow_O1_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentRow_Fe3A_Text_2 = {"container": easyDiffraction_ContentArea, "occurrence": 3, "text": "Pb", "type": "Text", "unnamed": 1, "visible": True}
contentRow_1_Text = {"container": contentListView_contentRow_Rectangle_6, "text": 1, "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text_2 = {"container": contentListView_contentRow_Rectangle_7, "text": "0.0000", "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 136, "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_10 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "occurrence": 4, "source": "C:/util/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
easyDiffraction_iso_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "χiso", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_contentListView_ListView_5 = {"container": easyDiffraction_QQuickApplicationWindow, "id": "contentListView", "occurrence": 5, "type": "ListView", "unnamed": 1, "visible": True}
easyDiffraction_23_Text = {"container": easyDiffraction_QQuickApplicationWindow, "text": "χ23", "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_9 = {"container": easyDiffraction_contentListView_ListView_5, "id": "contentRow", "index": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_5 = {"container": contentListView_contentRow_Rectangle_9, "occurrence": 10, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_4 = {"container": contentListView_contentRow_Rectangle_9, "occurrence": 5, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_8 = {"container": easyDiffraction_contentListView_ListView_5, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_3 = {"container": contentListView_contentRow_Rectangle_8, "occurrence": 4, "type": "Text", "unnamed": 1, "visible": True}
contentRow_O1_Text_3 = {"container": contentListView_contentRow_Rectangle_9, "text": "O1", "type": "Text", "unnamed": 1, "visible": True}
contentRow_2_Text = {"container": contentListView_contentRow_Rectangle_8, "text": 2, "type": "Text", "unnamed": 1, "visible": True}
contentRow_0_0000_Text_3 = {"container": contentListView_contentRow_Rectangle_8, "occurrence": 3, "text": "0.0000", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_bottomChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_QQuickApplicationWindow, "id": "bottomChart", "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
contentRow_qwe_TextInput = {"backgroundcolor": "#2a99d9", "container": contentListView_contentRow_Rectangle, "echoMode": 0, "id": "qwe", "type": "TextInput", "unnamed": 1, "visible": True}
easyDiffraction_sliderHandle_Rectangle = {"container": easyDiffraction_QQuickApplicationWindow, "id": "sliderHandle", "type": "Rectangle", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_12 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 24, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_4 = {"checkable": True, "container": easyDiffraction_ContentArea, "occurrence": 18, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_11 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 17, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_3 = {"checkable": True, "container": easyDiffraction_ContentArea, "occurrence": 14, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_10 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 8, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_CheckBox_2 = {"checkable": True, "container": easyDiffraction_ContentArea, "occurrence": 2, "type": "CheckBox", "unnamed": 1, "visible": True}
contentListView_Rectangle = {"container": contentListView_contentRow_Rectangle_12, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_9 = {"container": contentListView_contentRow_Rectangle_12, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_13 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 1, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_8 = {"container": contentListView_contentRow_Rectangle_13, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentRow_Text_7 = {"container": contentListView_contentRow_Rectangle_10, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_contentRow_Rectangle_14 = {"container": easyDiffraction_contentListView_ListView, "id": "contentRow", "index": 18, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_Text_6 = {"container": contentListView_contentRow_Rectangle_14, "occurrence": 3, "type": "Text", "unnamed": 1, "visible": True}
contentListView_Rectangle_2 = {"container": easyDiffraction_ContentArea, "occurrence": 9, "type": "ScrollBar", "unnamed": 1, "visible": True}
easyDiffraction_label_MnemonicLabel_8 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "label", "occurrence": 11, "type": "MnemonicLabel", "visible": True}
o_Rectangle = {"container": easyDiffraction_Overlay, "occurrence": 3, "type": "Rectangle", "unnamed": 1, "visible": True}
optimization_terminated_successfully_Number_of_evaluations_of_the_objective_functions_120_Number_of_iterations_performed_by_the_optimizer_15_Final_goodnes_of_fit_3_00_Label = {"container": easyDiffraction_Overlay, "text": "Desired error not necessarily achieved due to precision loss.\n\nGoodness-of-fit (χ²): 332.39\nNum. refined parameters: 1", "type": "Text", "unnamed": 1, "visible": True}
o_Rectangle_2 = {"container": easyDiffraction_Overlay, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_qwe_TextInput_2 = {"backgroundcolor": "#ffffff", "container": contentListView_contentRow_Rectangle_10, "echoMode": 0, "id": "qwe", "type": "TextInput", "unnamed": 1, "visible": True}
contentRow_0_0008_Text = {"container": contentListView_contentRow_Rectangle, "text": "0.0008", "type": "Text", "unnamed": 1, "visible": True}
easyDiffraction_Text_9 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 92, "type": "Text", "unnamed": 1, "visible": True}
tabBar_Report_TabButton = {"checkable": True, "container": tabBar_tabBar_TabBar, "text": "Report", "type": "TabButton", "unnamed": 1, "visible": True}
easyDiffraction_textArea_TextArea = {"container": easyDiffraction_QQuickApplicationWindow, "id": "textArea", "type": "TextArea", "unnamed": 1, "visible": True}
easyDiffraction_exportFileExt_ComboBox = {"container": easyDiffraction_QQuickApplicationWindow, "id": "exportFileExt", "type": "ComboBox", "unnamed": 1, "visible": True}
easyDiffraction_Export_as_GroupBox = {"container": easyDiffraction_QQuickApplicationWindow, "title": "Export as...", "type": "GroupBox", "unnamed": 1, "visible": True}
easyDiffraction_Export_Button = {"checkable": False, "container": easyDiffraction_QQuickApplicationWindow, "id": "exportButton", "text": "Export", "type": "Button", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_11 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "C:/util/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Fonts/Awesome/svgs/arrow-circle-right.svg", "type": "IconImage", "visible": True}
tabBar_label_MnemonicLabel_2 = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "label", "type": "MnemonicLabel", "visible": True}
easyDiffraction_Text_10 = {"container": easyDiffraction_QQuickApplicationWindow, "occurrence": 136, "type": "Text", "unnamed": 1, "visible": True}
contentRow_ColorImage = {"container": contentListView_contentRow_Rectangle, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentRow_ColorImage_2 = {"container": contentListView_contentRow_Rectangle_10, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentListView_Rectangle_3 = {"container": easyDiffraction_contentListView_ListView, "index": 0, "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
contentRow_ColorImage_3 = {"container": contentListView_contentRow_Rectangle_11, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
contentRow_ColorImage_4 = {"container": contentListView_contentRow_Rectangle_12, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
unknow_problems_during_refinement_Label = {"container": easyDiffraction_Overlay, "text": "Unknow problems during refinement", "type": "Label", "unnamed": 1, "visible": True}
label_MnemonicLabel_3 = {"container": easyDiffraction_ContentArea, "objectName": "label", "type": "MnemonicLabel", "visible": True}
open_an_existing_project_Open = {"checkable": False, "container": easyDiffraction_ContentArea, "id": "openButton", "text": "Open an existing project", "type": "Open", "unnamed": 1, "visible": True}
tabBar_Home_Home = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Home", "type": "Home", "unnamed": 1, "visible": True}
tabBar_Sample_Sample = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Sample", "type": "Sample", "unnamed": 1, "visible": True}
tabBar_Experiment_Experiment = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Experiment", "type": "Experiment", "unnamed": 1, "visible": True}
tabBar_Analysis_Analysis = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Analysis", "type": "Analysis", "unnamed": 1, "visible": True}
tabBar_Summary_Summary = {"checkable": True, "container": easyDiffraction_tabBar_TabBar_2, "text": "Summary", "type": "Summary", "unnamed": 1, "visible": True}
easyDiffraction_image_IconImage_12 = {"container": easyDiffraction_QQuickApplicationWindow, "objectName": "image", "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Fonts/Awesome/svgs/cog.svg", "type": "IconImage", "visible": True}
automatically_check_for_updates_CheckBox = {"checkable": True, "container": easyDiffraction_Overlay, "text": "Automatically check for updates", "type": "CheckBox", "unnamed": 1, "visible": True}
o_ComboBox = {"container": easyDiffraction_Overlay, "type": "ComboBox", "unnamed": 1, "visible": True}
o_ComboBox_2 = {"container": easyDiffraction_Overlay, "occurrence": 2, "type": "ComboBox", "unnamed": 1, "visible": True}
o_ComboBox_3 = {"container": easyDiffraction_Overlay, "occurrence": 3, "type": "ComboBox", "unnamed": 1, "visible": True}
label_MnemonicLabel_4 = {"container": easyDiffraction_ContentArea, "objectName": "label", "occurrence": 4, "type": "MnemonicLabel", "visible": True}
o_Text = {"container": easyDiffraction_ContentArea, "occurrence": 11, "type": "Text", "unnamed": 1, "visible": True}
open_Dialog = {"text": "Open", "type": "Dialog"}
open_Cancel_Button = {"container": open_Dialog, "text": "Cancel", "type": "Button"}
open_Edit = {"container": open_Dialog, "type": "Edit"}
pbSO4_Text = {"container": easyDiffraction_ContentArea, "text": "PbSO4\n", "type": "Text", "unnamed": 1, "visible": True}
unpolarised_neutron_diffraction_powder_1d_Text = {"container": easyDiffraction_ContentArea, "text": "unpolarised neutron diffraction, powder, 1d", "type": "Text", "unnamed": 1, "visible": True}
project_Keywords_Text = {"container": easyDiffraction_ContentArea, "text": "Project Keywords:", "type": "Text", "unnamed": 1, "visible": True}
phases_Text = {"container": easyDiffraction_ContentArea, "occurrence": 2, "text": "Phases:", "type": "Text", "unnamed": 1, "visible": True}
pd_Text = {"container": easyDiffraction_ContentArea, "text": "pd", "type": "Text", "unnamed": 1, "visible": True}
pbSO4_Text_2 = {"container": easyDiffraction_ContentArea, "text": "PbSO4", "type": "Text", "unnamed": 1, "visible": True}
o6T2_at_LLB_Text = {"container": easyDiffraction_ContentArea, "text": "6T2 at LLB", "type": "Text", "unnamed": 1, "visible": True}
tabBar_TabBar_2 = {"container": easyDiffraction_ContentArea, "id": "tabBar", "occurrence": 3, "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_tabBar_TabBar_3 = {"container": tabBar_TabBar_2, "id": "tabBar", "type": "TabBar", "unnamed": 1, "visible": True}
tabBar_Structure_View_TabButton_2 = {"checkable": True, "container": tabBar_tabBar_TabBar_3, "text": "Structure View", "type": "TabButton", "unnamed": 1, "visible": True}
tabBar_Text_View_TabButton_2 = {"checkable": True, "container": tabBar_tabBar_TabBar_3, "text": "Text View", "type": "TabButton", "unnamed": 1, "visible": True}
o_TextArea = {"container": easyDiffraction_ContentArea, "type": "TextArea", "unnamed": 1, "visible": True}
tabBar_image_IconImage = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "image", "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Fonts/Awesome/svgs/gem.svg", "type": "IconImage", "visible": True}
image_IconImage = {"container": easyDiffraction_ContentArea, "objectName": "image", "occurrence": 3, "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
o0_9079_Text = {"container": easyDiffraction_ContentArea, "occurrence": 3, "text": "0.9079", "type": "Text", "unnamed": 1, "visible": True}
o0_1872_Text = {"container": easyDiffraction_ContentArea, "text": "0.1872", "type": "Text", "unnamed": 1, "visible": True}
o0_0643_Text = {"container": easyDiffraction_ContentArea, "occurrence": 2, "text": "0.0643", "type": "Text", "unnamed": 1, "visible": True}
image_IconImage_2 = {"container": easyDiffraction_ContentArea, "objectName": "image", "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-down.svg", "type": "IconImage", "visible": True}
image_IconImage_3 = {"container": easyDiffraction_ContentArea, "objectName": "image", "occurrence": 4, "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
image_IconImage_4 = {"container": easyDiffraction_ContentArea, "objectName": "image", "occurrence": 5, "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
image_IconImage_5 = {"container": easyDiffraction_ContentArea, "objectName": "image", "occurrence": 6, "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Icons/triangle-right.svg", "type": "IconImage", "visible": True}
tabBar_label_MnemonicLabel_3 = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "label", "occurrence": 5, "type": "MnemonicLabel", "visible": True}
topChart_QtCharts_DeclarativeChart = {"container": easyDiffraction_ContentArea, "id": "topChart", "occurrence": 2, "type": "QtCharts::DeclarativeChart", "unnamed": 1, "visible": True}
o_TextInput = {"backgroundcolor": "#2a99d9", "container": easyDiffraction_ContentArea, "echoMode": 0, "type": "TextInput", "unnamed": 1, "visible": True}
start_fitting_PausePlay = {"checkable": False, "container": easyDiffraction_ContentArea, "id": "pausePlayButton", "text": "Start fitting", "type": "PausePlay", "unnamed": 1, "visible": True}
ang_Text = {"container": easyDiffraction_ContentArea, "text": "ang", "type": "Text", "unnamed": 1, "visible": True}
o0_0001_Text = {"container": easyDiffraction_ContentArea, "text": "0.0001", "type": "Text", "unnamed": 1, "visible": True}
tabBar_label_MnemonicLabel_4 = {"container": easyDiffraction_tabBar_TabBar_2, "objectName": "label", "occurrence": 6, "type": "MnemonicLabel", "visible": True}
export_Export = {"checkable": False, "container": easyDiffraction_ContentArea, "id": "exportButton", "text": "Export", "type": "Export", "unnamed": 1, "visible": True}
o_ColorImage = {"container": easyDiffraction_ContentArea, "occurrence": 2, "source": "qrc:/qt-project.org/imports/QtQuick/Controls.2/images/check.png", "type": "ColorImage", "unnamed": 1, "visible": True}
image_IconImage_6 = {"container": easyDiffraction_ContentArea, "objectName": "image", "source": "C:/Program Files (x86)/easyDiffraction/easyDiffraction/QmlImports/easyAnalysis/Resources/Fonts/Awesome/svgs/play-circle.svg", "type": "IconImage", "visible": True}
phases_PbSO4_atoms_S_fract_z_Text = {"container": easyDiffraction_ContentArea, "text": "phases PbSO4 atoms S fract_z", "type": "Text", "unnamed": 1, "visible": True}
o_Text_2 = {"container": easyDiffraction_ContentArea, "occurrence": 360, "type": "Text", "unnamed": 1, "visible": True}
o_Rectangle_3 = {"container": easyDiffraction_ContentArea, "occurrence": 432, "type": "Rectangle", "unnamed": 1, "visible": True}
no_parameters_selected_for_refinement_Text = {"container": easyDiffraction_Overlay, "text": "No parameters selected for refinement", "type": "Text", "unnamed": 1, "visible": True}
start_Simulation_Refinement_TabButton = {"checkable": True, "container": easyDiffraction_ContentArea, "id": "analysisButton", "text": "Start Simulation/Refinement", "type": "TabButton", "unnamed": 1, "visible": True}
about_easyDiffraction_Text = {"container": easyDiffraction_ContentArea, "text": "About easyDiffraction", "type": "Text", "unnamed": 1, "visible": True}
end_User_Licence_Agreement_Text = {"container": easyDiffraction_Overlay, "text": "End User Licence Agreement", "type": "Text", "unnamed": 1, "visible": True}
dependent_Open_Source_Licenses_Text = {"container": easyDiffraction_Overlay, "text": "Dependent Open Source Licenses", "type": "Text", "unnamed": 1, "visible": True}
online_Documentation_Text = {"container": easyDiffraction_ContentArea, "text": "Online Documentation", "type": "Text", "unnamed": 1, "visible": True}
get_in_Touch_Online_Text = {"container": easyDiffraction_ContentArea, "text": "Get in Touch Online", "type": "Text", "unnamed": 1, "visible": True}
o_QQuickApplicationWindow = {"title": " ", "type": "QQuickApplicationWindow", "unnamed": 1, "visible": True}
easyDiffraction_Redo = {"checkable": False, "container": o_QQuickApplicationWindow, "occurrence": 3, "type": "ToolButton", "unnamed": 1, "visible": True}
easyDiffraction_Undo = {"checkable": False, "container": o_QQuickApplicationWindow, "occurrence": 2, "type": "ToolButton", "unnamed": 1, "visible": True}
easyDiffraction_SaveState = {"checkable": False, "container": o_QQuickApplicationWindow, "type": "ToolButton", "unnamed": 1, "visible": True}
o_Bug = {"checkable": False, "container": o_QQuickApplicationWindow, "occurrence": 7, "type": "ToolButton", "unnamed": 1, "visible": True}
o_Help = {"checkable": False, "container": o_QQuickApplicationWindow, "occurrence": 6, "type": "ToolButton", "unnamed": 1, "visible": True}
o_contentArea_ContentArea = {"container": o_QQuickApplicationWindow, "id": "contentArea", "type": "ContentArea", "unnamed": 1, "visible": True}
o_appContainer_Rectangle = {"container": o_QQuickApplicationWindow, "id": "appContainer", "type": "Rectangle", "unnamed": 1, "visible": True}
contentArea_Start_SideBarButton = {"checkable": False, "container": o_contentArea_ContentArea, "id": "startButton", "text": "Start", "type": "SideBarButton", "unnamed": 1, "visible": True}
contentArea_items_SwipeView = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 2, "type": "SwipeView", "unnamed": 1, "visible": True}
create_a_new_project_Create = {"checkable": False, "container": contentArea_items_SwipeView, "text": "Create a new project", "type": "SideBarButton", "unnamed": 1, "visible": True}
items_Create_a_new_project_Label = {"container": contentArea_items_SwipeView, "text": "Create a new project", "type": "Label", "unnamed": 1, "visible": True}
items_Open_an_existing_project_SideBarButton = {"checkable": False, "container": contentArea_items_SwipeView, "text": "Open an existing project", "type": "SideBarButton", "unnamed": 1, "visible": True}
o_appBarCentralTabs_AppBarCentralTabs = {"container": o_QQuickApplicationWindow, "id": "appBarCentralTabs", "type": "AppBarCentralTabs", "unnamed": 1, "visible": True}
appBarCentralTabs_Home_AppBarTabButton = {"checkable": True, "container": o_appBarCentralTabs_AppBarCentralTabs, "text": "Home", "type": "AppBarTabButton", "unnamed": 1, "visible": True}
appBarCentralTabs_Sample_AppBarTabButton = {"checkable": True, "container": o_appBarCentralTabs_AppBarCentralTabs, "text": "Sample", "type": "AppBarTabButton", "unnamed": 1, "visible": True}
appBarCentralTabs_Experiment_AppBarTabButton = {"checkable": True, "container": o_appBarCentralTabs_AppBarCentralTabs, "id": "experimentTabButton", "text": "Experiment", "type": "AppBarTabButton", "unnamed": 1, "visible": True}
appBarCentralTabs_Analysis_AppBarTabButton = {"checkable": True, "container": o_appBarCentralTabs_AppBarCentralTabs, "id": "analysisTabButton", "text": "Analysis", "type": "AppBarTabButton", "unnamed": 1, "visible": True}
appBarCentralTabs_Summary_AppBarTabButton = {"checkable": True, "container": o_appBarCentralTabs_AppBarCentralTabs, "id": "summaryTabButton", "text": "Summary", "type": "AppBarTabButton", "unnamed": 1, "visible": True}
o_label_MnemonicLabel = {"container": o_QQuickApplicationWindow, "objectName": "label", "occurrence": 5, "type": "MnemonicLabel", "visible": True}
o_Overlay = {"container": o_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
view_SwipeView = {"container": o_Overlay, "id": "view", "type": "SwipeView", "unnamed": 1, "visible": True}
view_toolTipsCheckBox_CheckBox = {"checkable": True, "container": view_SwipeView, "id": "toolTipsCheckBox", "type": "CheckBox", "unnamed": 1, "visible": True}
bar_TabBar = {"container": o_Overlay, "id": "bar", "type": "TabBar", "unnamed": 1, "visible": True}
bar_Rectangle = {"container": bar_TabBar, "occurrence": 17, "type": "Rectangle", "unnamed": 1, "visible": True}
view_Check_now_SideBarButton = {"checkable": False, "container": view_SwipeView, "text": "Check now", "type": "SideBarButton", "unnamed": 1, "visible": True}
view_ComboBox = {"container": view_SwipeView, "type": "ComboBox", "unnamed": 1, "visible": True}
view_ComboBox_2 = {"container": view_SwipeView, "occurrence": 2, "type": "ComboBox", "unnamed": 1, "visible": True}
view_ComboBox_3 = {"container": view_SwipeView, "occurrence": 3, "type": "ComboBox", "unnamed": 1, "visible": True}
view_ComboBox_4 = {"container": view_SwipeView, "occurrence": 4, "type": "ComboBox", "unnamed": 1, "visible": True}
view_languageSelector_ComboBox = {"container": view_SwipeView, "id": "languageSelector", "type": "ComboBox", "unnamed": 1, "visible": True}
view_ComboBox_5 = {"container": view_SwipeView, "occurrence": 6, "type": "ComboBox", "unnamed": 1, "visible": True}
view_ComboBox_6 = {"container": view_SwipeView, "occurrence": 7, "type": "ComboBox", "unnamed": 1, "visible": True}
appBarCentralTabs_Rectangle = {"container": o_appBarCentralTabs_AppBarCentralTabs, "occurrence": 20, "type": "Rectangle", "unnamed": 1, "visible": True}
items_Rectangle = {"container": contentArea_items_SwipeView, "occurrence": 39, "type": "Rectangle", "unnamed": 1, "visible": True}
contentArea_items_SwipeView_2 = {"container": o_contentArea_ContentArea, "id": "items", "type": "SwipeView", "unnamed": 1, "visible": True}
items_TextInput_2 = {"backgroundcolor": "#ffffff", "container": contentArea_items_SwipeView_2, "echoMode": 0, "occurrence": 2, "type": "TextInput", "unnamed": 1, "visible": True}
items_TextInput = {"backgroundcolor": "#ffffff", "container": contentArea_items_SwipeView_2, "echoMode": 0, "type": "TextInput", "unnamed": 1, "visible": True}
contentArea_items_SwipeView_3 = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 3, "type": "SwipeView", "unnamed": 1, "visible": True}
items_structureView_WebEngineView = {"container": contentArea_items_SwipeView_3, "id": "structureView", "type": "WebEngineView", "unnamed": 1, "visible": True}
o_ToolButton = {"checkable": False, "container": o_QQuickApplicationWindow, "occurrence": 4, "type": "ToolButton", "unnamed": 1, "visible": True}
o_container_container_container_o_QQuickApplicationWindow_id_contentArea_type_ContentArea_unnamed_1_visible_true_id_items_occurrence_5_type_SwipeView_unnamed_1_visible_true_type_ExperimentDataChartBokeh_unnamed_1_visible_true_chartView_0_DOCUMENT_HTML1 = "{container={container={container=':o_QQuickApplicationWindow' id='contentArea' type='ContentArea' unnamed='1' visible='true'} id='items' occurrence='5' type='SwipeView' unnamed='1' visible='true'} type='ExperimentDataChartBokeh' unnamed='1' visible='true'}.chartView_0.DOCUMENT.HTML1"
contentArea_items_SwipeView_4 = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 5, "type": "SwipeView", "unnamed": 1, "visible": True}
items_chartView_WebEngineView = {"container": contentArea_items_SwipeView_4, "id": "chartView", "type": "WebEngineView", "unnamed": 1, "visible": True}
contentArea_items_SwipeView_5 = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 8, "type": "SwipeView", "unnamed": 1, "visible": True}
items_valueColumn_TableViewTextInput = {"backgroundcolor": "#fefefe", "container": contentArea_items_SwipeView_5, "echoMode": 0, "id": "valueColumn", "type": "TableViewTextInput", "unnamed": 1, "visible": True}
items_Rectangle_2 = {"container": contentArea_items_SwipeView_5, "occurrence": 149, "type": "Rectangle", "unnamed": 1, "visible": True}
items_AnalysisFitables = {"container": contentArea_items_SwipeView_5, "type": "AnalysisFitables", "unnamed": 1, "visible": True}
o_container_container_container_o_QQuickApplicationWindow_id_contentArea_type_ContentArea_unnamed_1_visible_true_id_items_occurrence_9_type_SwipeView_unnamed_1_visible_true_id_webView_type_WebEngineView_unnamed_1_visible_true_DOCUMENT = "{container={container={container=':o_QQuickApplicationWindow' id='contentArea' type='ContentArea' unnamed='1' visible='true'} id='items' occurrence='9' type='SwipeView' unnamed='1' visible='true'} id='webView' type='WebEngineView' unnamed='1' visible='true'}.DOCUMENT"
contentArea_items_SwipeView_6 = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 9, "type": "SwipeView", "unnamed": 1, "visible": True}
items_webView_WebEngineView = {"container": contentArea_items_SwipeView_6, "id": "webView", "type": "WebEngineView", "unnamed": 1, "visible": True}
contentArea_items_SwipeView_7 = {"container": o_contentArea_ContentArea, "id": "items", "occurrence": 10, "type": "SwipeView", "unnamed": 1, "visible": True}
items_Export_report_GroupBox = {"container": contentArea_items_SwipeView_7, "title": "Export report", "type": "GroupBox", "unnamed": 1, "visible": True}
o_container_contentArea_items_SwipeView_4_id_chartView_type_WebEngineView_unnamed_1_visible_true_DOCUMENT_HTML1 = "{container=':contentArea_items_SwipeView_4' id='chartView' type='WebEngineView' unnamed='1' visible='true'}.DOCUMENT.HTML1"
contentArea_rocket_Label = {"container": o_contentArea_ContentArea, "text": "rocket", "type": "Label", "unnamed": 1, "visible": True}
contentArea_Start_Label = {"container": o_contentArea_ContentArea, "text": "Start", "type": "Label", "unnamed": 1, "visible": True}
